name: boost
on:
  push:


jobs:
  example:
    runs-on: [ubuntu-18.04]
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.5
      with:
        cmake-version: '3.16.1'

    - name: Setup python
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Check version
      run: |
        cmake --version
        python --version
        echo -e '#include <boost/version.hpp>\nBOOST_VERSION' | gcc -x c++ -E  -
