name: python
on:
  push:


jobs:
  example:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - run: python --version
